### ISSUE TITLE
 It doesn't work, I will supposedly update it for 10.3 but it keeps telling me it's not up to date

### ISSUE THREAD

**Issue by CharizardR** [ensoulsharp-io/EnsoulSharp.Dependencies#26]
It doesn't work, I will supposedly update it for 10.3 but it keeps telling me it's not up to date

**Comment by Demonivm** [comment]
> 
> 
> It doesn't work, I will supposedly update it for 10.3 but it keeps telling me it's not up to date

I think that's because there's a 10.3.1 hotfix
