### ISSUE TITLE
Target selector search mode issue

### ISSUE THREAD

**Issue by yunyty** [ensoulsharp-io/EnsoulSharp.Dependencies#37]
Hello,

Target selector not working correctly.
I made a video about it. Please check the video. https://streamable.com/rfgnmc
In the video, I set Min Health to 100, but Caitlyn still hit Lux while Lux had 6200 HP instead of Amumu only having 800 HP (orbwalker should attack Amumu).
I also set Amumu priority to 5, but orbwalker still attack Lux.

**Comment by Bravable** [comment]
will have new ts to replace it
