### ISSUE TITLE
How could I use it on TW Server

### ISSUE THREAD

**Issue by li0122** [ensoulsharp-io/EnsoulSharp.Dependencies#42]
For Taiwan Server, the application version is still on 12.1.416.5961. How could I run this script on League of Legends. Thanks for developers!

**Comment by EnsoulSharp** [comment]
1) make sure your ensoul ver match to riot 12.1
2) replace 12.1 riot ver hotfix to your game folder
3) create "iwanttogetbanned" folder within install dir to prevent auto update
4) enjoy
