### ISSUE TITLE
Enshoul sharp not working

### ISSUE THREAD

**Issue by El-Mundos** [ensoulsharp-io/EnsoulSharp.Dependencies#44]
Hey, when i open LOL Enshoul Sharp jsut doesnt works, just as if i executed the game normally, no watermark on screen and hotkeys dont do anything too.

**Comment by krisoft20** [comment]
seems dx9 issue, I suggest you to force League Client to use dx9 legacy or set it manually in config (game.cfg)

**Comment by El-Mundos** [comment]
Thank you!!! It solved the problem! :)

**Comment by El-Mundos** [comment]
oh and is ensoulsharp detected? And if i get banned is it just the account or the whole PC? And is it any way to get unbanned my PC if it gets banned?
