### ISSUE TITLE
same problem "lol version not supported"

### ISSUE THREAD

**Issue by mk5mad** [ensoulsharp-io/EnsoulSharp.Dependencies#5]
league of legends version not supported, this usually means that lol updated and ensoulsharp didn't update yet.
what can i do?

**Comment by dandelionus** [comment]
I think they only update it for a specific server.

**Comment by yasinl33t** [comment]
This cheat is only for CN users.

It wont work for any EU Region and NA.

**Comment by dandelionus** [comment]
But why tho? Are their AC different?

**Comment by shisuiemeuamigo** [comment]
ja da pra quem é do brasil?

**Comment by shisuiemeuamigo** [comment]
Who is it for from America?
