### ISSUE TITLE
Problem with the update

### ISSUE THREAD

**Issue by Hayuzaa** [ensoulsharp-io/EnsoulSharp.Dependencies#51]

**Comment by Hayuzaa** [comment]
My ensoulsharp loader don't accept to update because there's no match with league version. The new lol version is from 29 april, what can i do ?

**Comment by krisoft20** [comment]
drag drop those files after you login to the client
https://www.mediafire.com/file/vzxx4f77w96fpd7/hotfix12.8_garena.rar/file

then use Ensoulsharp.Updater

**Comment by Hayuzaa** [comment]
i can't load the loader because it's not updated

**Comment by Hayuzaa** [comment]
or the lol client ?

**Comment by ImWayden** [comment]
hey ! where can i download the 12.9 hotfix ? if it exist
