### ISSUE TITLE
 Can't join tg group（Chat Group）

### ISSUE THREAD

**Issue by ghost** [ensoulsharp-io/EnsoulSharp.Dependencies#54]

**Comment by Aiigiae** [comment]
The game version ： 12.12.448.6653 China
I'm just wondering why the watermark is sometimes displayed in the game and sometimes not. The admin said I had a different version of the game and told me to stop asking such stupid questions. But actually, there is no problem with the game version.

**Comment by Bravable** [comment]
https://t.me/+VncSJsmL7YHZKq14
