### ISSUE TITLE
Forum?

### ISSUE THREAD

**Issue by dandelionus** [ensoulsharp-io/EnsoulSharp.Dependencies#6]
Can you please link the forum or Discord server if you have?

**Comment by JinxBR** [comment]
I want too!

**Comment by seskral2662** [comment]
+1

**Comment by fexolol** [comment]
+1

**Comment by TheCrazyLion** [comment]
fucking banned fron discord and lost server adress https://ibb.co/ZSpCdrX  Nikos was my acc

**Comment by emvipanhvip789** [comment]
Bán acc rác all sever giá rẻ 
Facebook.com/dattricker123
